[project]
name = "bakery"
version = "0.0.1"
description = "static visualizations for relay"
requires-python = ">=3.10"
dependencies = [
    "cmap>=0.5.0",
    "einops>=0.8.0",
    "h3>=4.0.0a0",
    "lxml>=5.3.0",
    "matplotlib>=3.10.0",
    "mrcfile>=1.5.3",
    "numpy>=2.2.1",
    "pydantic>=2.10.5",
    "scikit-image>=0.24.0",
    "scipy>=1.15.1",
    "starfile>=0.5.11",
    "tifffile>=2024.8.30",
    "typer>=0.15.1",
    "imodmodel>=0.0.15",
]
classifiers = ["Private :: Do Not Upload"]

[project.scripts]
bakery = "bakery:cli"