<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <EnableDefaultContentItems>true</EnableDefaultContentItems>
    </PropertyGroup>
    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Refund.Tests" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.*" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.*" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.0" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.14.0" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
        <PackageReference Include="NaturalSort.Extension" Version="4.4.1" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="VYaml" Version="1.2.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Emoji\Emoji.csproj" />
        <ProjectReference Include="..\SourceGenerators\RelaySourceGenerators\RelaySourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Warp\WarpLib\WarpLib.csproj" />
        <ProjectReference Include="..\ElkSharp\src\ElkSharp\ElkSharp.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Components\FileBrowser\FileBrowser.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\ThumbnailPanel\ThumbnailPanel.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\Jobs\ExpandedView\LogPanel.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\FourierSpace\AmplitudeSpectrumViewer.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\SlimTextField\SlimTextField.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\CodeEditor\CodeEditor.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="Components\Emoji\EmojiSelector.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Components\DurationText.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\refund.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\css\refund.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\css\prism-light.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\css\prism-dark.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\prism.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\relaySession.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\webgl-isosurface-shared.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Components\SingleAxisScatter\SingleAxisScatter.razor.js" />
        <Content Include="Components\SingleAxisScatter\SingleAxisScatter.razor.js" />
        <None Remove="Components\GlobalTooltip\GlobalTooltipContainer.razor.js" />
        <Content Include="Components\GlobalTooltip\GlobalTooltipContainer.razor.js" />
        <None Remove="Components\TomogramViewer\TomogramViewer.razor.js" />
        <Content Include="Components\TomogramViewer\TomogramViewer.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Components\TomogramViewerJs\TomogramViewerJs.razor.js" />
        <Content Include="Components\TomogramViewerJs\TomogramViewerJs.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Components\MicrographViewer\MicrographViewer.razor.js" />
        <Content Include="Components\MicrographViewer\MicrographViewer.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Components\Histogram\Histogram.razor.js" />
        <Content Include="Components\Histogram\Histogram.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\images\mlogo.png">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>