using System.Globalization;
using Refund.DataModel;
using Refund.DataModel.ReadOnly;
using Refund.JobResources;
using Refund.UIFields;
using Refund.Utils;
using Warp;
using Warp.Tools;

namespace Refund.Jobs.Common.Tools.ExpandSymmetry;

/// <summary>
/// Expands the symmetry of a RELION particle set by wrapping <c>relion_particle_symmetry_expand</c>,
/// creating symmetrically equivalent copies of every particle. Point-group expansion replicates each
/// particle once per symmetry operator; helical expansion replicates once per asymmetric unit.
///
/// The RELION tool preserves the optics table and every non-orientation column itself. It does not
/// know about the tomogram list or optimisation set, so for tomo inputs this job adapts the
/// optimisation_set.star (repointing it at the expanded particles) in <see cref="Stage"/> while
/// leaving the tomograms STAR file untouched.
/// </summary>
[GenerateReadOnly]
public class ExpandSymmetry : RelionJob, IClusterJob
{
    public override int2 CardSquareCount { get; set; } = new int2(1, 1);

    public override string TypeGuid => "f4e8a1c2-9b7d-4e3a-8c15-6d2b0f9a3e71";

    public override string TypeCategory => "Common.Tools.Expand symmetry";

    public override string TypeName => "Expand symmetry";

    public override string TypeNameShort => "Expand sym";

    public override string TypeDescription => "Create symmetrically equivalent copies of RELION particles using relion_particle_symmetry_expand";

    public override JobQueueType QueueType => JobQueueType.CPU;

    /// <summary>CPU-only tool; requests no GPUs.</summary>
    public override int GpuCount => 0;

    public override Type ExpandedViewType => null;

    public override bool IsIterative => false;

    /// <summary>
    /// Port name constants
    /// </summary>
    public const string PortInParticles = "Particles";
    public const string PortOutParticles = "Particles";

    #region Parameters

    [UiBool("helix", "Helical symmetry",
            helpText: "Expand a helical symmetry instead of a point group. When enabled, provide the " +
                      "twist, rise and number of asymmetric units to replicate.")]
    [RelayProperty]
    public bool DoHelical { get; set; } = false;

    [UiSymmetry("sym", "Symmetry",
                helpText: "Point-group symmetry to expand, e.g. C3. Each particle is replicated once " +
                          "per symmetry operator.",
                ConditionalOnField = nameof(DoHelical),
                ConditionalOnValue = false)]
    [RelayProperty]
    public string Symmetry { get; set; } = "C1";

    [UiInt("asu", "Asymmetric units",
           min: 2, max: 999, stepSize: 1,
           helpText: "Number of helical asymmetric units to expand. Each particle is replicated this many times.",
           ConditionalOnField = nameof(DoHelical),
           ConditionalOnValue = true)]
    [RelayProperty]
    public int HelicalUnits { get; set; } = 2;

    [UiDecimal("twist", "Helical twist",
               min: -180, max: 180, stepSize: 0.001,
               unit: "°",
               helpText: "Twist of the helical symmetry to expand, in degrees.",
               ConditionalOnField = nameof(DoHelical),
               ConditionalOnValue = true)]
    [RelayProperty]
    public decimal HelicalTwist { get; set; } = 0m;

    [UiDecimal("rise", "Helical rise",
               min: 0, max: 100000, stepSize: 0.001,
               unit: "Å",
               helpText: "Rise of the helical symmetry to expand, in Angstrom.",
               ConditionalOnField = nameof(DoHelical),
               ConditionalOnValue = true)]
    [RelayProperty]
    public decimal HelicalRise { get; set; } = 0m;

    [UiString("", "Additional arguments",
              isAdvanced: true,
              helpText: "Command-line arguments passed verbatim to relion_particle_symmetry_expand that " +
                        "are not generated by the GUI, e.g. --frac_sampling or --ignore_optics. Specify " +
                        "as --option1 value1 --option2 value2")]
    [RelayProperty]
    public string AdditionalArguments { get; set; } = "";

    #endregion

    #region Serialized state

    /// <summary>
    /// Number of particles in the expanded output, filled in after the run to populate the output resource.
    /// </summary>
    [RelayProperty]
    [Clearable]
    public int ExpandedParticleCount { get; set; } = 0;

    #endregion

    #region Results paths

    private const string ResExpandedStar = "expanded.star";
    private const string ResOptimisationSetStar = "optimisation_set.star";

    /// <summary>
    /// Full path to the expanded particle STAR file produced by RELION.
    /// </summary>
    public string ResExpandedStarFile => Path.Combine(DirectoryPath, ResExpandedStar);

    /// <summary>
    /// Full path to the adapted optimisation_set.star file (tomo only).
    /// </summary>
    public string ResOptimisationSetStarFile => Path.Combine(DirectoryPath, ResOptimisationSetStar);

    #endregion

    public ExpandSymmetry()
    {
        var portInParticles = new PortIn(this, typeof(ParticleSet), PortInParticles, "Particles", 1, 1);

        PortsIn = new(new Dictionary<string, PortIn>
        {
            [portInParticles.Name] = portInParticles
        });

        var portOutParticles = new PortOut(this, typeof(ParticleSet), PortOutParticles, "Particles", GetParticleSetResource);

        PortsOut = new(new Dictionary<string, PortOut>
        {
            [portOutParticles.Name] = portOutParticles
        });
    }

    #region Resource locators

    private ParticleSet GetParticleSetResource(int iter)
    {
        if (!PortsIn[PortInParticles].IsConnected)
            return null;

        ParticleSet result = PortsIn[PortInParticles].GetSingleResource<ParticleSet>();
        if (result == null)
            return null;

        result.ParticlesSingleStarPath = ResExpandedStarFile;

        if (!string.IsNullOrEmpty(result.OptimisationSetStarPath))
            result.OptimisationSetStarPath = ResOptimisationSetStarFile;

        if (ExpandedParticleCount > 0)
            result.ParticleCount = ExpandedParticleCount;

        return result;
    }

    #endregion

    public override string CommandName => "relion_particle_symmetry_expand";

    public override Dictionary<string, string> ComposeCommandArguments()
    {
        // Base composition emits either --sym (point group) or --helix/--twist/--rise/--asu
        // (helical), based on the DoHelical toggle and each field's conditional visibility.
        var result = base.ComposeCommandArguments();

        if (!string.IsNullOrWhiteSpace(AdditionalArguments))
            foreach (var kv in ArgumentStringToDictionary(AdditionalArguments))
                result[kv.Key] = kv.Value;

        ParticleSet particles = PortsIn[PortInParticles].GetSingleResource<ParticleSet>();
        if (particles == null)
            throw new Exception("Particle set input not found.");
        if (!particles.HasSingleStar)
            throw new Exception("Input must have a single STAR file (multi-STAR directories are not supported).");

        result["i"] = Space.GetRelativePath(particles.ParticlesSingleStarPath);
        result["o"] = Space.GetRelativePath(ResExpandedStarFile);

        // RELION's helical expansion takes the pixel size from the input rather than a UI field.
        if (DoHelical)
            result["angpix"] = ((float)particles.CoordPixelSize).ToString(CultureInfo.InvariantCulture);

        return result;
    }

    public override void Stage()
    {
        base.Stage();

        // relion_particle_symmetry_expand only writes the expanded particle STAR (preserving the
        // optics table). It knows nothing about the optimisation set or tomograms STAR, so for tomo
        // inputs we write an adapted optimisation set here, repointing it at the expanded particles
        // while leaving the tomograms STAR untouched.
        //
        // This is done in Stage() (before the command runs) rather than in FinalizeRun(), because
        // cluster jobs transition straight to Finished on completion without a finalize step — the
        // optimisation set only stores the path of the expanded STAR, which is known ahead of time.
        ParticleSet particles = PortsIn[PortInParticles].GetSingleResource<ParticleSet>();

        if (particles != null && !string.IsNullOrEmpty(particles.OptimisationSetStarPath))
        {
            Directory.CreateDirectory(DirectoryPath);
            AdaptOptimisationSet(particles.OptimisationSetStarPath, ResOptimisationSetStarFile,
                                 Space.GetRelativePath(ResExpandedStarFile));
        }
    }

    /// <summary>
    /// Copies an optimisation_set.star, repointing its rlnTomoParticlesFile entry at the expanded
    /// particles STAR file. Every other entry (including the tomograms file) is preserved.
    /// </summary>
    internal static void AdaptOptimisationSet(string inputPath, string outputPath, string relativeParticlesPath)
    {
        var setTable = new StarParameters(inputPath);
        if (setTable.HasColumn("rlnTomoParticlesFile"))
            setTable.SetRowValue(0, "rlnTomoParticlesFile", relativeParticlesPath);
        setTable.Save(outputPath);
    }

    private long _lastLogSize = -1;

    public override Action TrackProgressLogs()
    {
        JobTools.EnsureResultsDirectory(RelayResultsDirectoryPath);

        int maxLogsExist = -1;

        if (JobTools.HasLogFileChanged(PathStdOut, ref _lastLogSize))
        {
            maxLogsExist = 0;

            string[] logLines = File.ReadAllText(PathStdOut).Split('\n');
            logLines = JobTools.CleanProgressBarLines(logLines);

            JobTools.WriteLogFile(string.Join('\n', logLines), LogFilePath(0));
        }
        else if (File.Exists(PathStdOut))
        {
            maxLogsExist = Math.Max(maxLogsExist, LogsAvailableIteration);
        }

        if (maxLogsExist > LogsAvailableIteration)
            return () => { LogsAvailableIteration = maxLogsExist; };

        return null;
    }

    public override Action TrackProgressResults()
    {
        JobTools.EnsureResultsDirectory(RelayResultsDirectoryPath);

        // Record the expanded particle count once RELION has written the output, so the output
        // resource reports the right number. Called on completion (and while running); guarded to
        // run its work only once. The optimisation set is written earlier, in Stage().
        if (ExpandedParticleCount > 0 || !File.Exists(ResExpandedStarFile))
            return null;

        int count = Star.IsMultiTable(ResExpandedStarFile)
            ? new Star(ResExpandedStarFile, "particles").RowCount
            : new Star(ResExpandedStarFile).RowCount;

        return () => ExpandedParticleCount = count;
    }
}
