<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceGenerators\RelaySourceGenerators\RelaySourceGenerators.csproj"  OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="fluentui-emoji/assets/**/metadata.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.14.0" />
    </ItemGroup>
</Project>