using Microsoft.AspNetCore.Components;
using Microsoft.FluentUI.AspNetCore.Components;
using Icons = Microsoft.FluentUI.AspNetCore.Components.Icons;

namespace Refund.Components.Class2DSelection;

/// <summary>
/// Component for displaying and selecting 2D class averages from a pre-generated atlas image.
/// Enables users to visualize, sort, and select class averages generated from 2D classification jobs.
/// 
/// This component is primarily used within the Class2DExpandedView to display classification results
/// and provide an interactive interface for researchers to select promising particle classes for
/// further processing. The component maintains selection state that can be accessed by parent components
/// to create downstream jobs based on class selections.
/// </summary>
public partial class Class2DSelection
{
    /// <summary>
    /// Path to the class atlas image file generated by Bakery.
    /// This contains all class average images tiled horizontally in a single PNG.
    /// 
    /// In Class2DExpandedView, this is typically set to the value returned by:
    /// <code>_job.VisClassAtlas(_expandedViewService.CurrentVisIteration)</code>
    /// which references a Bakery-generated atlas for the current iteration.
    /// </summary>
    [Parameter]
    public required string ClassAtlasImagePath { get; set; } = null;

    /// <summary>
    /// Total number of class images available in the atlas file.
    /// 
    /// Typically set to the value of <code>_job.NClasses</code> in Class2DExpandedView,
    /// which represents the number of classes generated by the 2D classification algorithm.
    /// </summary>
    [Parameter]
    public required int NImagesInFile { get; set; }

    /// <summary>
    /// Array specifying the position of each class in the atlas.
    /// Used to map between class indices and their positions in the image strip.
    /// 
    /// In Class2DExpandedView, this is typically set to:
    /// <code>_classNumbers</code> (generated as Enumerable.Range(1, _job.NClasses).ToArray())
    /// which provides a 1-indexed array of class positions.
    /// </summary>
    [Parameter]
    public required int[] ClassPositionsInAtlas { get; set; }

    /// <summary>
    /// Array of class IDs, used for identification and sorting.
    /// 
    /// In Class2DExpandedView, this is populated from a deserialized JSON file containing
    /// class statistics, using: 
    /// <code>class2DModels.Select(m => m.Id).ToArray()</code>
    /// </summary>
    [Parameter]
    public int[] ClassIds { get; set; }

    /// <summary>
    /// Array of estimated resolution values for each class, in Angstroms.
    /// Used for information display and optional sorting.
    /// 
    /// In Class2DExpandedView, this is populated from class metadata using:
    /// <code>class2DModels.Select(m => m.Resolution.Value).ToArray()</code>
    /// when Resolution values are available in the class statistics file.
    /// </summary>
    [Parameter]
    public float[] ClassResolutions { get; set; }

    /// <summary>
    /// Array of estimated class sizes or distribution percentages.
    /// Used for information display and optional sorting.
    /// 
    /// In Class2DExpandedView, this is populated from class metadata using:
    /// <code>class2DModels.Select(m => m.Distribution.Value).ToArray()</code>
    /// when Distribution values are available. These values represent the percentage
    /// of particles that belong to each class, displayed as percentages in the UI.
    /// </summary>
    [Parameter]
    public float[] ClassSizes { get; set; }

    /// <summary>
    /// Size in pixels for each rendered class image.
    /// Controls the display size of each thumbnail.
    /// 
    /// Typically set to 128 pixels in Class2DExpandedView to provide a detailed
    /// but compact display of multiple class averages.
    /// </summary>
    [Parameter]
    public required int RenderedImageSidelengthPx { get; set; }

    /// <summary>
    /// Spacing between class images in pixels.
    /// Controls the grid layout density.
    /// 
    /// Typically set to 6 pixels in Class2DExpandedView.
    /// </summary>
    [Parameter]
    public required int SpacingPx { get; set; }

    /// <summary>
    /// Width of the border around each class image in pixels.
    /// Used to highlight selection state.
    /// 
    /// Typically set to 4 pixels in Class2DExpandedView for clear visual distinction.
    /// </summary>
    [Parameter]
    public int BorderWidthPx { get; set; } = 2;

    /// <summary>
    /// CSS color for the border of unselected class images.
    /// 
    /// Typically set to "transparent" in Class2DExpandedView to hide the border
    /// around unselected classes.
    /// </summary>
    [Parameter]
    public string BorderColorUnselected { get; set; } = "transparent";

    /// <summary>
    /// CSS color for the border of selected class images.
    /// 
    /// Typically set to "#fd7e14" (orange) in Class2DExpandedView to highlight 
    /// selected classes with a prominent border.
    /// </summary>
    [Parameter]
    public string BorderColorSelected { get; set; } = "mediumpurple";

    /// <summary>
    /// Whether to display sorting options for the class images.
    /// When true, enables sorting by ID, resolution, or size.
    /// 
    /// This is enabled by default in Class2DExpandedView to help researchers
    /// identify the most promising classes based on different metrics.
    /// </summary>
    [Parameter]
    public bool AllowSorting { get; set; } = true;

    /// <summary>
    /// Callback invoked when the selection state changes.
    /// Parent components can use this to react to selection changes.
    /// 
    /// In Class2DExpandedView, this calls a SelectionChanged method that updates
    /// a count of selected classes and refreshes the UI to update action button states.
    /// </summary>
    [Parameter]
    public Action OnSelectionChanged { get; set; }

    /// <summary>
    /// Controls whether the selection state can be modified by user interaction.
    /// When false, the component becomes read-only.
    /// </summary>
    [Parameter]
    public bool SelectionIsMutable { get; set; } = true;

    private Guid guid = Guid.NewGuid();

    /// <summary>
    /// Set of 1-indexed class indices that are currently selected.
    /// This is the core state that tracks which classes are selected.
    /// 
    /// In Class2DExpandedView, this is accessed directly through a component reference to:
    /// - Clear all selections: <code>_class2DSelectionComponent.selectedClasses.Clear()</code>
    /// - Add all selections: <code>_class2DSelectionComponent.selectedClasses.Add(classNumber)</code>
    /// - Get selected count: <code>_class2DSelectionComponent.selectedClasses.Count</code>
    /// - Create selection jobs: <code>selectedClasses.Order().ToArray()</code>
    /// </summary>
    public HashSet<int> selectedClasses = new();

    // Implementation details
    private string previousClassAtlasImagePath = null;
    private string classAtlasImageUrl = null;

    /// <summary>
    /// Handles parameter changes when the component is initialized or updated.
    /// Loads or reloads the class atlas image when the image path changes.
    /// 
    /// This is particularly important when the parent component (Class2DExpandedView)
    /// updates the iteration being displayed, which changes the ClassAtlasImagePath.
    /// </summary>
    protected override async Task OnParametersSetAsync()
    {
        if(ClassAtlasImagePath != previousClassAtlasImagePath)
        {
            previousClassAtlasImagePath = ClassAtlasImagePath;
            await LoadClassAtlasImage();
        }
    }

    /// <summary>
    /// Loads the class atlas image from the specified path and converts it to a data URL.
    /// This enables embedding the image directly in the HTML without additional HTTP requests.
    /// 
    /// The atlas is a single PNG image generated by Bakery that contains all class averages
    /// arranged horizontally, which is more efficient than loading individual images.
    /// </summary>
    private async Task LoadClassAtlasImage()
    {
        if(!string.IsNullOrWhiteSpace(ClassAtlasImagePath))
        {
            classAtlasImageUrl = await GetBase64PngUrlFromPath(ClassAtlasImagePath);
        }
    }

    /// <summary>
    /// Generates the CSS style for a class image tile to properly position it within the sprite.
    /// Uses background-position to show the correct portion of the atlas image.
    /// 
    /// This CSS positioning technique allows the component to display the appropriate
    /// section of the atlas for each class without creating separate image elements.
    /// </summary>
    /// <param name="classNumber">The 1-indexed class number to display</param>
    /// <returns>CSS background-position style string for the specified class</returns>
    private string GetTileStyle(int classNumber)
    {
        var linearIndex = classNumber - 1;

        return $@"background-position: -{linearIndex * RenderedImageSidelengthPx}px 0px;";
    }

    /// <summary>
    /// Toggles the selection state of a class image when clicked.
    /// Adds or removes the class from the selected set and triggers the selection changed event.
    /// 
    /// This is the primary interaction point for researchers to select which classes
    /// to include in downstream processing. Selected classes can later be exported to 
    /// create a new Class2DSelect job that filters particles based on these selections.
    /// </summary>
    /// <param name="classNumber">The 1-indexed class number to toggle</param>
    private void ToggleSelection(int classNumber)
    {
        if(!SelectionIsMutable)
        {
            return;
        }

        if(selectedClasses.Contains(classNumber))
        {
            selectedClasses.Remove(classNumber);
        }
        else
        {
            selectedClasses.Add(classNumber);
        }

        OnSelectionChanged?.Invoke();

        StateHasChanged();
    }

    /// <summary>
    /// Reads an image file from disk and converts it to a base64-encoded data URL.
    /// This allows embedding the image directly in HTML without requiring a separate HTTP request.
    /// 
    /// Since class atlas images are generated by Bakery and stored locally, this approach
    /// provides efficient access to the visualization data without network overhead.
    /// </summary>
    /// <param name="path">File system path to the image file</param>
    /// <returns>Base64-encoded data URL of the image, or empty string if the file doesn't exist</returns>
    private async Task<string> GetBase64PngUrlFromPath(string path)
    {
        if(File.Exists(path))
        {
            var fileBytes = await File.ReadAllBytesAsync(path);
            var fileBase64 = Convert.ToBase64String(fileBytes);

            return $"data:image/png;base64,{fileBase64}";
        }

        return "";
    }

    #region Sorting
    /// <summary>
    /// Available options for sorting class images.
    /// These options correspond to the different metadata available for each class.
    /// 
    /// Sorting helps researchers identify the most promising classes based on different
    /// criteria such as resolution (quality) or size (particle distribution).
    /// </summary>
    private static List<Option<string>> SortOptions { get; } = new()
    {
        new Option<string> { Value = "ID", Text = "ID" },
        new Option<string> { Value = "Resolution", Text = "Resolution" },
        new Option<string> { Value = "Size", Text = "Size" }
    };

    /// <summary>
    /// Currently selected sort option.
    /// </summary>
    private Option<string> SelectedSortOption = SortOptions.First();
    
    /// <summary>
    /// Gets the current sort option value for use in sorting logic.
    /// </summary>
    private string SortOption => SelectedSortOption.Value;
    
    /// <summary>
    /// Determines the sort direction (ascending or descending).
    /// </summary>
    private bool SortIsAscending { get; set; } = true;

    /// <summary>
    /// Icon to display when sort is ascending.
    /// </summary>
    private Icon IconSortAscending = new Icons.Regular.Size20.ArrowSortUpLines();
    
    /// <summary>
    /// Icon to display when sort is descending.
    /// </summary>
    private Icon IconSortDescending = new Icons.Regular.Size20.ArrowSortDownLines();
    
    /// <summary>
    /// Gets the appropriate sort icon based on current sort direction.
    /// </summary>
    private Icon IconSort => SortIsAscending ? IconSortAscending : IconSortDescending;

    /// <summary>
    /// Toggles between ascending and descending sort direction.
    /// </summary>
    private void ToggleSortDirection()
    {
        SortIsAscending = !SortIsAscending;
    }

    /// <summary>
    /// Handles sort option selection changes from the dropdown.
    /// </summary>
    /// <param name="e">The newly selected sort option</param>
    private void OnSortOptionChanged(Option<string> e)
    {
        SelectedSortOption = e;
    }

    /// <summary>
    /// Calculates the sorted order of class indices based on the current sort criteria and direction.
    /// This is used to determine the display order of class images in the grid.
    /// 
    /// Sorting by resolution is particularly useful in cryo-EM workflows as it helps
    /// researchers quickly identify the highest-quality class averages, which often
    /// correspond to the best-resolved structural features.
    /// </summary>
    /// <returns>
    /// Array of indices representing the sorted order of classes.
    /// These indices correspond to positions in the ClassPositionsInAtlas array.
    /// </returns>
    private int[] ClassOrderSorted()
    {
        var indices = Enumerable.Range(0, ClassPositionsInAtlas.Length).ToArray();

        if(SortOption == "ID" && ClassIds != null)
        {
            return (SortIsAscending
                ? indices.OrderBy(i => ClassIds[i])
                : indices.OrderByDescending(i => ClassIds[i])).ToArray();
        }

        if(SortOption == "Resolution" && ClassResolutions != null)
        {
            return (SortIsAscending
                ? indices.OrderBy(i => ClassResolutions[i])
                : indices.OrderByDescending(i => ClassResolutions[i])).ToArray();
        }

        if(SortOption == "Size" && ClassSizes != null)
        {
            return (SortIsAscending
                ? indices.OrderBy(i => ClassSizes[i])
                : indices.OrderByDescending(i => ClassSizes[i])).ToArray();
        }

        // If no metadata for sorting is available, just use the original order or reverse it
        return SortIsAscending ? indices : indices.Reverse().ToArray();
    }
    #endregion
}