using System.Text.Json;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using Refund.Components.Jobs.ExpandedView;
using Refund.DataModel.ReadOnly;
using Refund.Jobs.Refinement.Classes3D.Class3D;
using Refund.Services;

namespace Refund.Jobs.Refinement.Classes3D.Class3DSelect;

/// <summary>
/// Expanded view component for the Class3DSelect job, displaying detailed visualizations
/// of the selected 3D class volumes, their statistics, and associated analytical plots.
/// </summary>
/// <remarks>
/// This component is referenced by the Class3DSelect job's ExpandedViewType property
/// and is automatically instantiated when a user expands a Class3DSelect job in the UI.
/// Unlike the Class3DExpandedView, this component is read-only and doesn't allow further
/// class selection since it already represents a selection operation.
/// </remarks>
public partial class Class3DSelectExpandedView
{
    /// <summary>
    /// Service for managing expanded job view state and interactions.
    /// Used to track the currently displayed job and respond to job updates.
    /// </summary>
    [Inject] private ExpandedJobViewService ExpandedViewService { get; set; }
    
    /// <summary>
    /// The strongly typed reference to the current Class3DSelect job being displayed.
    /// </summary>
    private ReadOnlyClass3DSelect _job;
    
    /// <summary>
    /// Flag indicating whether to display masked or unmasked volumes.
    /// </summary>
    private bool _isMaskChecked;
    
    /// <summary>
    /// Reference to JavaScript module for potential client-side interactions.
    /// </summary>
    private IJSObjectReference _module;
    
    /// <summary>
    /// Deserialized class models containing statistics about the selected classes.
    /// Includes properties like resolution, particle distribution, etc.
    /// </summary>
    private Class3DModel[] _class3DModels;

    /// <summary>
    /// Initializes the component by subscribing to job change events and loading the initial job data.
    /// </summary>
    protected override async Task OnInitializedAsync()
    {
        base.OnInitialized();
        
        // Subscribe to job change and update events from the ExpandedJobViewService
        ExpandedViewService.OnJobChanged += HandleJobChanged;
        ExpandedViewService.OnJobUpdated += HandleJobUpdated;
        
        // Initialize with the currently displayed job
        await HandleJobChanged(ExpandedViewService.CurrentJob);
    }

    /// <summary>
    /// Handles changes to the displayed job, updating the component state when a new job is selected.
    /// </summary>
    /// <param name="job">The newly selected job to display</param>
    private async Task HandleJobChanged(ReadOnlyJob job)
    {
        // Only proceed if the job is a Class3DSelect job
        if (job is ReadOnlyClass3DSelect class3DSelect)
        {
            _job = class3DSelect;
            UpdateData();
        }
        else
        {
            _job = null;
        }
        
        await InvokeAsync(StateHasChanged);
    }

    /// <summary>
    /// Handles updates to the current job, refreshing the displayed data.
    /// </summary>
    private async Task HandleJobUpdated()
    {
        UpdateData();
        await InvokeAsync(StateHasChanged);
    }

    /// <summary>
    /// Loads class statistics data from the job's visualization files.
    /// </summary>
    /// <remarks>
    /// This method deserializes the class statistics JSON file generated by the job,
    /// which contains metadata about each class such as resolution and particle distribution.
    /// </remarks>
    private void UpdateData()
    {
        if (_job == null)
            return;

        try
        {
            // Load class statistics if available
            if (File.Exists(_job.VisClassStats))
            {
                _class3DModels = JsonSerializer.Deserialize<Class3DModel[]>(File.ReadAllText(_job.VisClassStats));
            }
            else
            {
                _class3DModels = null;
            }
        }
        catch { }
    }
    
    /// <summary>
    /// Cleans up resources by unsubscribing from events when the component is disposed.
    /// </summary>
    public async ValueTask DisposeAsync()
    {
        ExpandedViewService.OnJobChanged -= HandleJobChanged;
        ExpandedViewService.OnJobUpdated -= HandleJobUpdated;
    }
}